// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Peaje.Data;

#nullable disable

namespace Peaje.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240617131913_MigracionPeajeUno")]
    partial class MigracionPeajeUno
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Peaje.Models.PeajesM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombrePeaje")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.Property<int>("categoriaTarifaId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("fechaRegistro")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("PeajeM");
                });
#pragma warning restore 612, 618
        }
    }
}
